spring:
  output:
    ansi:
      enabled: ALWAYS
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB
server:
  port: 8012
#OSS配置
oss:
  aliyun-oss:
    access-key: 这里填写你的access key
    secret-key: 这里填写你的secret key
    bucket-name: turing-cloud-test
    enabled: true
    endpoint: oss-cn-shenzhen.aliyuncs.com
    https: true
