server:
  port: 8015
spring:
  main:
    allow-bean-definition-overriding: true

#短信配置
sms:
  aliyun:
    accessKeyId: 填写你的key
    accessKeySecret: 填写你的secret
    endpoint: dysmsapi.aliyuncs.com
    enabled: true