server:
  port: 8011

mqtt:
  username:
  password:
  keepAliveInterval: 60
  connectionTimeout: 7200
  urls: tcp://127.0.0.1:1883
  inbound:
    clientId: client-inbound
    topics: /#
    qos: 1
  outbound:
    clientId: client-outbound
    topic: /#